#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

# Create ChatWoot user
echo "Creating database role: ${CW_POSTGRES_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${CW_POSTGRES_USER} WITH CREATEDB PASSWORD '${CW_POSTGRES_PASSWORD}';
ALTER USER ${CW_POSTGRES_USER} WITH SUPERUSER;

CREATE USER ${TB_POSTGRES_USER} WITH CREATEDB PASSWORD '${TB_POSTGRES_PASSWORD}';
ALTER USER ${TB_POSTGRES_USER} WITH SUPERUSER;

CREATE USER ${N8N_POSTGRES_USER} WITH CREATEDB PASSWORD '${N8N_POSTGRES_PASSWORD}';
ALTER USER ${N8N_POSTGRES_USER} WITH SUPERUSER;

CREATE DATABASE ${CW_POSTGRES_DB} OWNER ${CW_POSTGRES_USER};

CREATE DATABASE ${TB_POSTGRES_DB} OWNER ${TB_POSTGRES_USER};

CREATE DATABASE ${N8N_POSTGRES_DB} OWNER ${N8N_POSTGRES_USER};
EOSQL